### ISSUE TITLE
3 repeat move draw is not implemented

### ISSUE THREAD

**Issue by mightysquirrel** [MiSTer-devel/Chess#1]
I just wanted to leave a comment. On level 7, the 3 repeat move draw is not implemented, and the AI does not know to avoid it.

**Comment by RobertPeip** [comment]
Thanks for comment.

Yes threefold is not implemented at all and I agree that this weakens the AI a bit in endgame situations where it would be winning otherwise.

It's even worse:
All complex draw situations are missing: fivefold, fifty-move rule or impossible situations are also not done.
Only stalemate is.

The reason is simple: it requires a lot of additional checking. While threefold would be "ok" to implement, fivefold already requires the whole history of the game to be checked for any new position.
It also requires interaction with the player, asking if he wants to claim the draw or not.

But honestly, all this is only really important when you play against another AI. 

In Human vs AI it doesn't really matter for threefold:
- if you get a threefold and had a better position before: accept that it is draw without the game stating it
- if you get a threefold and had a worse position before: accept that you lost or move something else

In the fivefold, fifty-move and "not enough material" situations, you can just stop the game.
There is no highscore or rating, so why bother with such a boring situation?


Overall, this is not just a simple "rule is missing" situation, but quiet some work, which I will most likely not invest.

But i leave it up to you if you want to close or keep it open for someone else in the future who wants to do it.

**Comment by mightysquirrel** [comment]
AH ok, no worries. I didn't know it was a limitation. I will close it. Thank you for the reply!
